### ISSUE TITLE
spring-turbo-modules 可否提供多一些Example？

### ISSUE THREAD

**Issue by zhhaojie** [yingzhuo/spring-turbo-modules#159]
[spring-turbo-modules](https://github.com/yingzhuo/spring-turbo-modules) 关注很久了，代码非常精简，老道，非常赞，能否多提供一些Example。担心在实际项目当中，使用方式不正确。 谢谢！

**Comment by yingzhuo** [comment]
@zhhaojie 谢谢您关注，本项目是我一个个人风格很重的东西，API向下兼容我很少考虑，如果您用在生产环境建议谨慎考虑。

您的建议我会认真考虑，会添加更多的Example。
